version: "3.8"

services:
  redis:
    image: "redis:6.0.9-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis-data: {}
